local Test = require("tests/support/Test")

require("tests/test_hex_geometry")
require("tests/test_card_field_geometry")
require("tests/test_action_zone")
require("tests/test_deck_generator")
require("tests/test_card_logic")
require("tests/test_deck_selection_menu")
require("tests/test_hex_grid_builder")
require("tests/test_hex_grid_menu")
require("tests/test_hex_grid")
require("tests/test_hex_object_spawner")
require("tests/test_hex_board_state")
require("tests/test_dungeon_map_state")
require("tests/test_turn_state")
require("tests/test_turn_system")
require("tests/test_settings_menu")
require("tests/test_game")

Test.run()
